### PR TITLE
Updating the theme to match the final project

### PR DESCRIPTION
**Pull request by lewisstevens1**
This change proposal is based on the output theme difference between the start and end of the project. With this included; input field text that looks white and does not match your videos.

### CODE REVIEW

**Comment by lewisstevens1** [comment]
Before:
Screenshot 2020-06-29 at 17 03 25

After:
Screenshot 2020-06-29 at 17 03 43

**Comment by lewisstevens1** [comment]
Related Issue:
https://github.com/londonappbrewery/flash-chat-flutter/issues/5

**Comment by jr00n** [comment]
Thanks!! Same issue here, couldn't find why..

**Comment by jr00n** [comment]
Hi @lewisstevens1 Angela is fixing this at the end of video/lesson 189

**Comment by fobf** [comment]
change `body1` to`bodyText1` in the main.dart

**Pull request closed without merging**
